import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import pptxgen from "pptxgenjs";
import { fileURLToPath } from "node:url";
import { loadTheme } from "./lib/theme.mjs";
import { renderDeck } from "./lib/render.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function parseArgs(argv) {
  const args = { input: "", output: "", theme: "" };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    const n = argv[i + 1];
    if (a === "--input") args.input = n || "";
    if (a === "--output") args.output = n || "";
    if (a === "--theme") args.theme = n || "";
  }
  return args;
}

async function main() {
  const { input, output, theme } = parseArgs(process.argv.slice(2));
  if (!input) throw new Error("missing --input");
  if (!theme) throw new Error("missing --theme");

  const inputPath = path.isAbsolute(input) ? input : path.resolve(process.cwd(), input);
  const outputPath = output
    ? path.isAbsolute(output)
      ? output
      : path.resolve(process.cwd(), output)
    : path.resolve(process.cwd(), "output.pptx");

  const deck = JSON.parse(await fs.readFile(inputPath, "utf8"));
  const selectedTheme = await loadTheme(theme, path.resolve(__dirname, ".."));

  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_16x9";
  pptx.author = deck?.meta?.author || "";
  pptx.title = deck?.meta?.title || "";
  pptx.subject = "Generated by pptx skill";

  pptx.theme = {
    headFontFace: selectedTheme.fonts.head,
    bodyFontFace: selectedTheme.fonts.body,
    lang: "zh-CN"
  };

  await renderDeck(pptx, deck, selectedTheme);

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await pptx.writeFile({ fileName: outputPath });
  process.stdout.write(outputPath + "\n");
}

main().catch((err) => {
  process.stderr.write(String(err?.stack || err?.message || err) + "\n");
  process.exit(1);
});
